name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  english_words: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/app_style/app_bg.jpg
    - images/app_style/ok.png
    - images/app_style/cancel.png
    - images/app_style/transform.png

    - images/artifacts/ring1.jpg
    - images/artifacts/ring2.jpg
    - images/artifacts/vial.jpg
    - images/artifacts/elixir.jpg

    - images/towns/castle.gif
    - images/towns/rampart.gif
    - images/towns/tower.gif
    - images/towns/inferno.gif
    - images/towns/dungeon.gif
    - images/towns/stronghold.gif
    - images/towns/fortress.gif
    - images/towns/conflux.gif
    - images/towns/cove.gif
    - images/towns/neutrals.jpg

    - images/units/castle/pikeman.gif
    - images/units/castle/archer.gif
    - images/units/castle/griffin.gif
    - images/units/castle/swordsman.gif
    - images/units/castle/monk.gif
    - images/units/rampart/centaur.gif
    - images/units/rampart/centaur_captain.gif
    - images/units/rampart/dwarf.gif
    - images/units/rampart/wood_elf.gif
    - images/units/rampart/pegasus.gif
    - images/units/rampart/dendroid.gif
    - images/units/tower/gremlin.gif
    - images/units/tower/mage.gif
    - images/units/tower/arch_mage.gif
    - images/units/tower/genie.gif
    - images/units/inferno/imp.gif
    - images/units/inferno/gog.gif
    - images/units/inferno/hell_hound.gif
    - images/units/inferno/demon.gif
    - images/units/inferno/pit_lord.gif
    - images/units/dungeon/troglodyte.gif
    - images/units/dungeon/infernal_troglodyte.gif
    - images/units/dungeon/harpy.gif
    - images/units/dungeon/beholder.gif
    - images/units/dungeon/medusa.gif
    - images/units/dungeon/medusa_queen.gif
    - images/units/dungeon/minotaur.gif
    - images/units/stronghold/goblin.gif
    - images/units/stronghold/wolf_rider.gif
    - images/units/stronghold/orc.gif
    - images/units/stronghold/orc_chieftain.gif
    - images/units/stronghold/ogre.gif
    - images/units/stronghold/roc.gif
    - images/units/fortress/gnoll.gif
    - images/units/fortress/lizzardman.gif
    - images/units/fortress/lizzard_warrior.gif
    - images/units/fortress/serpent_fly.gif
    - images/units/fortress/basilisk.gif
    - images/units/fortress/gorgon.gif
    - images/units/conflux/pixie.gif
    - images/units/cove/nymph.gif
    - images/units/cove/crew_mate.gif
    - images/units/cove/pirate.gif
    - images/units/cove/stormbird.gif
    - images/units/cove/sea_witch.gif
    - images/units/neutrals/peasant.gif
    - images/units/neutrals/halfling.gif
    - images/units/neutrals/rogue.gif
    - images/units/neutrals/boar.gif
    - images/units/neutrals/leprechaun.gif
    - images/units/neutrals/satyr.gif
    - images/units/neutrals/nomad.gif
    - images/units/neutrals/sharpshooter.gif
    - images/units/neutrals/fangarm.gif
    - images/units/neutrals/troll.gif
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
